### ISSUE TITLE
Globally Unique

### ISSUE THREAD

**Issue by rupamking1** [williamkapke/bson-objectid#40]
Is this id Globally Unique in distributed architecture?

**Comment by sagrawal31** [comment]
We recently encountered a big flaw in our database because this library is not able to generate a globally unique id. Can't rely on it unless the author comes and comment.

**Comment by titanism** [comment]
This library uses timestamps as that's the underlying mechanism. 

Ref: <https://github.com/williamkapke/bson-objectid/blob/master/objectid.js#L242-L252>

For something unique you should use `uuid` or something else.

**Comment by sagrawal31** [comment]
Thanks for the clarification @titanism. Curious to know, how this is different from https://github.com/mongodb/js-bson/blob/1.0-branch/lib/bson/objectid.js?

**Comment by titanism** [comment]
Please read the README description https://github.com/williamkapke/bson-objectid#bson-objectid-

https://github.com/williamkapke/bson-objectid/blob/master/objectid.js#L241-L274 versus https://github.com/mongodb/js-bson/blob/da8d8f1c0a9eaff7df6468a77e98282b8456cc3a/lib/bson/objectid.js#L151-L182

PR welcome for improvements

**Comment by williamkapke** [comment]
This library implements the same logic as Mongo's bson-objectid (see links above).

[Per Mongo](https://www.mongodb.com/blog/post/generating-globally-unique-identifiers-for-use-with-mongodb):
> ObjectID can be considered globally unique for all practical purposes.

All globally unique methods have some possibility of duplicates- it's just a matter of making it a really small chance. Everyone needs to identify how extreme their definition of "small chance" is. For Mongo- they're saying their algorithm covers "all practical purposes."

That's certainly open for interpretation!

**Comment by sagrawal31** [comment]
Thanks, @williamkapke for jumping in and replying. You are right, **Everyone needs to identify how extreme their definition of "small chance" is.**.

For us (where we offer a GA-like analytics SDK), we got ~950 duplicate identifiers. Upon investigation, we found that when our customers (who are using our SDK) websites when crawled by Google on daily basis, it was generating duplicate IDs very frequently that these 950 duplicates were generated just between 10th May to 6th of July.

We are assuming that this is because they must be using a hardware blueprint to launch multiple virtual devices.
